# inventory.sample.ini
# Copy this to 'inventory.ini' and adjust IPs/Names to match your kuargogo.yaml

[infra]
raspberry-pi ansible_host=192.168.1.100 ansible_user=debian

[server]
hp-prodesk ansible_host=192.168.1.101 ansible_user=debian

[agent]
lenovo-worker-1 ansible_host=192.168.1.102 ansible_user=debian
lenovo-worker-2 ansible_host=192.168.1.103 ansible_user=debian

[k3s_cluster:children]
server
agent

[gpu_nodes]
lenovo-worker-2 ansible_host=192.168.1.103 ansible_user=debian

[all:vars]
ansible_ssh_private_key_file=~/.ssh/kgg_cluster_id
ansible_port=22
