apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
spec:
  description: {{.Description | yamlQuote}}
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
