apiVersion: v1
kind: Secret
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  labels:
    argocd.argoproj.io/secret-type: repo-creds
    kargo.akuity.io/cred-type: {{.KargoCredType}}
type: Opaque
stringData:
  type: {{.SecretType}}
  url: {{.URL | yamlQuote}}
  repoURL: {{.RepoURL | yamlQuote}}
  {{- if eq .RepoURLIsRegex "true"}}
  repoURLIsRegex: "true"
  {{- end}}
  username: {{.Username | yamlQuote}}
  password: {{.Password | yamlQuote}}
