---
kargo_namespace: "kargo"
kargo_chart_version: "1.11.0"
kargo_ingress_host: "kargo.homelab"
kargo_admin_password_hash: ""
kargo_token_signing_key: "C#$I6Qxb90Eb4u^3ILK6WK7J"
kargo_argo_rollouts_enabled: true

